# Generated by Django 4.2.28 on 2026-02-04 17:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='cats', to='main.user')),
            ],
            options={
                'db_table': 'cats',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('food_from_owner', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=models.deletion.CASCADE, to='main.room')),
                ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingCat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='booking_cats', to='main.booking')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='main.cat')),
            ],
            options={
                'db_table': 'booking_cats',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['owner_user'], name='idx_cats_owner_user_id'),
        ),
        migrations.AddIndex(
            model_name='bookingcat',
            index=models.Index(fields=['booking'], name='idx_booking_cats_booking_id'),
        ),
        migrations.AddIndex(
            model_name='bookingcat',
            index=models.Index(fields=['cat'], name='idx_booking_cats_cat_id'),
        ),
        migrations.AddConstraint(
            model_name='bookingcat',
            constraint=models.UniqueConstraint(condition=models.Q(('cat__isnull', False)), fields=('booking', 'cat'), name='unique_booking_cat'),
        ),
        migrations.AddConstraint(
            model_name='bookingcat',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_cat_name__isnull', False)), fields=('booking', 'guest_cat_name'), name='unique_booking_guest_cat'),
        ),
        migrations.AddConstraint(
            model_name='bookingcat',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cat__isnull', False), ('guest_cat_name__isnull', True)), models.Q(('cat__isnull', True), ('guest_cat_name__isnull', False)), _connector='OR'), name='check_cat_reference'),
        ),
    ]
